### ISSUE TITLE
Large MagmaScript, errors, MySQL DB problems with too many connections

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3752]
**Describe the bug**
We have a dataset of 100k rows, and ~15 columns. One of the harmonisation scripts is very complex. Therefore when we are writing the script, we sometimes make a mistake (e.g. reference a variable that does not exist). When working on Opal connected to a MySQL database, if there are too many errors, the database complains about too many connections. While Opal continues to function, the summaries no longer load correctly so it is not possible to carry on with the work. A restart is needed to fix. This is difficult when working with cohorts that have to raise an IT ticket and it takes 2 weeks to restart the server....

Note that this problem first became apparent in 2 studies running the Coral stack, but was easier to reproduce in a Docker set up. The opal.log file doesn't seem to have any matching errors about MySQL:
[opal.log](https://github.com/obiba/opal/files/9119404/opal.log)

and the MySQL log doesn't have errors:
[mysql.log](https://github.com/obiba/opal/files/9119597/mysql.log)

![image](https://user-images.githubusercontent.com/8521654/179186370-11e352d3-356b-47e2-b408-0c9929f44386.png)

I also switched the DB to MongoDB and could not replicate the error.

**To Reproduce**
[mtc_synthetic.zip](https://github.com/obiba/opal/files/9119236/mtc_synthetic.zip)

1. Use the attached docker compose file to set up the system (I used a single CPU 10GB RAM VM Ubuntu 16)
2. Load the attached dataset and view into Opal
3. Go to the view, edit the script for variable test3, test the script
4. Go to other variables, ask for full summaries, go to test3, ask for full summaries
5. Repeat this a few times, eventually the MySQL errors will show up
6. Apologies that these steps are not very precise....

**Expected behavior**
Graceful failure, preferably with recovery. We need to write these complicated harmonisation scripts, and can't guarantee that we won't make mistakes as we are humans. Otherwise our options are:

- Only use implementations where Opal uses MongoDB (so we will need to remove Coral for now, and ask other studies to change their DB to Mongo)
- Change our harmonisation process to not use MagmaScript

**Comment by tombisho** [comment]
Without wishing to jump to conclusions, my interpretation is that when the MagmaScript error happens, somehow the MySQL connection is not closed. Thus you quickly reach the limit of the number of connections after encountering the errors a few times, and this remains until the stack is restarted.

**Comment by tombisho** [comment]
As it is not always that easy to reproduce this error, here is a video of it happening:

https://user-images.githubusercontent.com/8521654/182577590-1ec7cadd-a387-4cd2-abf1-e739f3488344.mp4

If you leave the system for a day and come back to it, the behaviour remains. There does not seem to be anything in the log that corresponds to this error (see the files I previously uploaded)

**Comment by kazoompa** [comment]
Hi Tom,

Does restarting the MySQL daemon resolve the issue?

**Comment by tombisho** [comment]
Hi Ramin, yes when you restart the system, the problem goes away. However the challenge is if you have to email someone, they have to raise a ticket with their IT and it takes a month, this can be an issue!

**Comment by tombisho** [comment]
MySQL config:

![image](https://user-images.githubusercontent.com/8521654/185432653-027f0e6f-79ce-465b-80e4-d3725e62d8d7.png)

**Comment by ymarcon** [comment]
For your info @tombisho I am currently upgrading the various database drivers and connection pool libs. Not an easy task, and in the meantime unfortunately I do not have a quick fix.

**Comment by ymarcon** [comment]
I may have a quick fix: the setting [org.obiba.opal.jdbc.maxPoolSize](https://opaldoc.obiba.org/en/latest/admin/configuration.html#miscelaneous-configuration) is for configuring a bigger pool of SQL connections. Default is 100, you can try to set a higher value.

**Comment by ymarcon** [comment]
I just built a new image `obiba/opal:snapshot` with many dependencies upgraded (db drivers, connection management etc.). Could you give it a try?

**Comment by tombisho** [comment]
> I may have a quick fix: the setting [org.obiba.opal.jdbc.maxPoolSize](https://opaldoc.obiba.org/en/latest/admin/configuration.html#miscelaneous-configuration) is for configuring a bigger pool of SQL connections. Default is 100, you can try to set a higher value.

Thanks for this suggestion. I tried setting it to 1000. The first result was that the table disappeared after modifying the config file, which was unexpected. The harmonised view was still there but had nothing to point to. I re-imported the data and went through the procedure above. It did not seem to make any difference and the maximum connections was quickly reached. I guess this would only ever be delaying the inevitable even if I set the max connections to 1,000,000

**Comment by ymarcon** [comment]
Thanks for the report! I tested in "dev" mode which bypasses the jars checks. I can reproduce in "prod" mode and will fix it.

**Comment by tombisho** [comment]
ok great, thank you!

**Comment by ymarcon** [comment]
Fixed, please try again.

**Comment by tombisho** [comment]
Thanks Yannick. I have tried but I'm afraid the error persists.

[opal.log](https://github.com/obiba/opal/files/9472584/opal.log)

To confirm the version of Opal is 4.5.0-SNAPSHOT

**Comment by ymarcon** [comment]
Please try again with the newest `obiba/opal:snapshot` image, I think I have fixed the issue (db cursor not closed on error).

**Comment by tombisho** [comment]
Hi Yannick, I'm really happy to say that it seems to have fixed the problem, and with the new image I am unable to break it 😄 Thank you! I hope now we can get this rolled out to Coral quickly.

So I think we can close the issue?

**Comment by ymarcon** [comment]
I would like to finish some Datashield related issues before releasing: #3744 and #3745. Maybe I can make a 4.4 patch release in the meantime?

**Comment by tombisho** [comment]
I will ask Gonçalo how quickly they will be able to update Coral, and whether they could make it possible for Coral to use the patch release

**Comment by tombisho** [comment]
Gonçalo has confirmed the best option is to make a patch release of 4.4 and they will just update their Opal image. Would that be OK?

**Comment by ymarcon** [comment]
I have just backported the fix, it was easy. Could you verify again with the updated `obiba/opal:snapshot` (which is now based on the 4.4.x development branch)?

**Comment by tombisho** [comment]
I get these errors:
[opal.log](https://github.com/obiba/opal/files/9496905/opal.log)
when I try and create a table

**Comment by ymarcon** [comment]
Sorry about that, some of the services were started in an undetermined order... It is fixed and the snapshot image has been updated.

**Comment by tombisho** [comment]
Thanks Yannick .... I tried again and there is still a bit of a problem:

![image](https://user-images.githubusercontent.com/8521654/188724287-bb48f225-2329-4649-bb50-36e530d8af15.png)

and the log:
[opal.log](https://github.com/obiba/opal/files/9500228/opal.log)

**Comment by ymarcon** [comment]
Ah I did not have the same behavior. I did a fix. Please try again with the updated snapshot image.

**Comment by tombisho** [comment]
Hi Yannick,

I am now a bit confused as we seem to be back to the original error

![image](https://user-images.githubusercontent.com/8521654/188843116-c9ecd5fc-f9e2-4f60-bcfb-7428c4e718fe.png)

but I don't see any problems in the log:

[opal.log](https://github.com/obiba/opal/files/9504720/opal.log)

**Comment by ymarcon** [comment]
Indeed this is confusing... I have verified, the snapshot image has the connection fix.

**Comment by tombisho** [comment]
I will check again, clearing the containers and pulling the snapshot image

**Comment by ymarcon** [comment]
Just tried locally with your mtc_synthetic example and had no issue when going through all values and (failing) summaries.

**Comment by tombisho** [comment]
even going to the summary of "test3" and hitting refresh 10+ times?

**Comment by ymarcon** [comment]
I just got the error :( seems to be related to the transient variable (the "Test" action).

**Comment by ymarcon** [comment]
Fixed, the approach was good, but a function was misused. I was able to test. Opal 4.4.11 is on its way.

**Comment by ymarcon** [comment]
4.4.11 is released.

**Comment by ymarcon** [comment]
By the way note that despite the connection pool max was 300, it was the Mysql driver that failed at 150 (+1) connections opened. So the limitation was on the database side. In the script there were 14 variables declared, that makes 14 connections for resolving the derived variable, and then after 10 attempts Mysql max was reached. Not sure how the Mysql max is calculated.

See default settings:

```
mysql> show variables like "max_connections";
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 151   |
+-----------------+-------+
1 row in set (0,12 sec)
```

Source: https://ubiq.co/database-blog/how-to-increase-max-connections-in-mysql/

**Comment by tombisho** [comment]
> 4.4.11 is released.

Great, thanks, Coral has also been updated

**Comment by tombisho** [comment]
> 

I guess this is a separate question about how we change that in the future, for example if we had a script that used 152 variables!?

**Comment by ymarcon** [comment]
Well in that case, use mongodb as it is much more flexible than the SQL databases!

**Comment by tombisho** [comment]
> Well in that case, use mongodb as it is much more flexible than the SQL databases!

Haha yes that is a fair point. I will ask Gonçalo whether they would consider moving Coral to mongodb....

**Comment by ymarcon** [comment]
Opal supports multiple databases, so you could have mongodb for one project and mysql for another in the same opal instance.

**Comment by tombisho** [comment]
Hi Ramin, yes a restart solves the problem.
